language: android
dist: trusty
sudo: required

group: edge

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25
    - extra-android-support
    - extra-android-m2repository
jdk:
  - oraclejdk8
env:
  global:
    - TERM=dumb
before_script:
  - export DATE=$(date)
  - export VERSION=$(date --date="$DATE" +'%Y%m%d%H%M%S')
script:
  - ./gradlew clean build